[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.28"  # Para criar janelas
pixels = "0.13" # Para renderização gráfica
tokio = { version = "1.0", features = ["full"] }